### ISSUE TITLE
Uncaught (in promise) Type Error: Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by user0608** [kyle-west/video-captain#12]
https://github.com/kyle-west/video-captain/blob/2efa4b2bfe67559fbd5154c3812bb8d82b4329d2/components/collection-browser.js#L57

Should be replaced with  `((episodes??[]).map(({ file })`, to avoid the error.

![image](https://user-images.githubusercontent.com/37247825/215327620-309d347e-fc86-4927-a8c4-aa4cb9e1e54e.png)

**Comment by kyle-west** [comment]
Thanks for the suggestion!
